environments:
  hex:
    - name: hex_r1_ukg
      networks:
        - subnet: 10.216.92.0/23
          gateway: 10.216.92.1
        - subnet: 10.216.101.0/24
          gateway: 10.216.101.1
    - name: hex_r3_ukg
      networks:
        - subnet: 10.216.94.0/23
          gateway: 10.216.94.1
    - name: hex_r8_ukg
      networks:
        - subnet: 10.216.96.0/23
          gateway: 10.216.96.1
    - name: hex_r12_ukg
      networks:
        - subnet: 10.216.98.0/23
          gateway: 10.216.98.1

  us:
    - name: us_r1_ukg
      networks:
        - subnet: 10.216.80.0/24
          gateway: 10.216.80.1
    - name: us_r3_ukg
      networks:
        - subnet: 10.216.81.0/24
          gateway: 10.216.81.1
    - name: us_r8_ukg
      networks:
        - subnet: 10.216.82.0/24
          gateway: 10.216.82.1
    - name: us_r12_ukg
      networks:
        - subnet: 10.216.83.0/24
          gateway: 10.216.83.1
    - name: us_ridder
      networks:
        - subnet: 10.164.200.0/24
          gateway: 10.164.200.1
    - name: us_altay
      networks:
        - subnet: 10.165.200.0/24
          gateway: 10.165.200.1
