from django.urls import path

from api import views

urlpatterns = [
    path("ui", views.ui_page, name="ui"),
    path("api/ui/config", views.ui_config, name="ui-config"),
    path("api/openapi.json", views.openapi_json_view, name="openapi-json"),
    path("api/docs", views.api_docs_view, name="api-docs"),
    path("api/auth/login", views.login_view, name="auth-login"),
    path("api/auth/totp", views.totp_verify_view, name="auth-totp"),
    path("api/auth/totp/setup", views.totp_setup_view, name="auth-totp-setup"),
    path("api/auth/totp/enable", views.totp_enable_view, name="auth-totp-enable"),
    path("api/auth/totp/disable", views.totp_disable_view, name="auth-totp-disable"),
    path("api/auth/logout", views.logout_view, name="auth-logout"),
    path("api/auth/change-password", views.change_password_view, name="auth-change-password"),
    path("api/auth/me", views.auth_me, name="auth-me"),
    path("api/auth/rbac", views.rbac_matrix_view, name="auth-rbac"),
    path("api/auth/api-keys", views.api_keys_dispatch, name="auth-api-keys"),
    path("api/auth/api-keys/<int:key_id>", views.api_key_detail, name="auth-api-key-detail"),
    path("api/auth/api-keys/<int:key_id>/revoke", views.api_key_revoke, name="auth-api-key-revoke"),
    path("api/auth/users", views.auth_users_dispatch, name="auth-users"),
    path("api/auth/users/<int:user_id>", views.auth_user_detail, name="auth-user-detail"),
    path("api/settings/oxidized", views.oxidized_settings_dispatch, name="settings-oxidized"),
    path("api/settings/backup", views.backup_settings_dispatch, name="settings-backup"),
    path("api/settings/backup/test-notify", views.backup_settings_test_notify, name="settings-backup-test-notify"),
    path("api/settings/backup/degrade-check", views.backup_settings_degrade_check, name="settings-backup-degrade-check"),
    path("api/settings/ldap", views.ldap_settings_dispatch, name="settings-ldap"),
    path("api/settings/ldap/test", views.ldap_settings_test_view, name="settings-ldap-test"),
    path("api/settings/git", views.git_settings_dispatch, name="settings-git"),
    path("api/settings/integrations", views.integration_settings_dispatch, name="settings-integrations"),
    path("api/settings/integrations/test-audit-webhook", views.integration_test_audit_webhook, name="settings-integrations-test-audit"),
    path("api/settings/scan", views.scan_settings_dispatch, name="settings-scan"),
    path("api/oxidized/health", views.oxidized_health, name="oxidized-health"),
    path("api/oxidized/logs", views.oxidized_logs, name="oxidized-logs"),
    path("api/oxidized/source", views.oxidized_source, name="oxidized-source"),
    path("api/oxidized/models", views.oxidized_models, name="oxidized-models"),
    path("oxidized-proxy", views.oxidized_proxy, name="oxidized-proxy-root"),
    path("oxidized-proxy/<path:path>", views.oxidized_proxy, name="oxidized-proxy"),
    path("api/oxidized/nodes", views.oxidized_nodes, name="oxidized-nodes"),
    path("api/oxidized/nodes/<str:name>", views.oxidized_node_show, name="oxidized-node-show"),
    path(
        "api/oxidized/nodes/<str:name>/versions",
        views.oxidized_node_versions,
        name="oxidized-node-versions",
    ),
    path(
        "api/oxidized/nodes/<str:name>/versions/<str:oid>",
        views.oxidized_node_version_view,
        name="oxidized-node-version-view",
    ),
    path(
        "api/oxidized/nodes/<str:name>/diff",
        views.oxidized_node_diff,
        name="oxidized-node-diff",
    ),
    path(
        "api/oxidized/nodes/<str:name>/fetch",
        views.oxidized_node_fetch,
        name="oxidized-node-fetch",
    ),
    path(
        "api/oxidized/nodes/<str:name>/backups",
        views.oxidized_node_backups,
        name="oxidized-node-backups",
    ),
    path(
        "api/oxidized/nodes/<str:name>/backups/run",
        views.oxidized_node_backups_run,
        name="oxidized-node-backups-run",
    ),
    path(
        "api/oxidized/nodes/<str:name>/backups/restore",
        views.oxidized_node_backups_restore,
        name="oxidized-node-backups-restore",
    ),
    path(
        "api/oxidized/nodes/<str:name>/backups/compare",
        views.oxidized_node_backups_compare,
        name="oxidized-node-backups-compare",
    ),
    path(
        "api/oxidized/nodes/<str:name>/backups/download",
        views.oxidized_node_backup_download,
        name="oxidized-node-backup-download",
    ),
    path("api/oxidized/backup/all", views.oxidized_backup_all, name="oxidized-backup-all"),
    path("health", views.health, name="health"),
    path("health/ready", views.health_ready, name="health-ready"),
    path("metrics", views.metrics_view, name="metrics"),
    path("inventory", views.inventory_dispatch, name="inventory"),
    path("inventory/devices/bulk", views.bulk_update_devices_view, name="inventory-devices-bulk"),
    path("inventory/devices", views.inventory_devices_dispatch, name="inventory-devices"),
    path("inventory/devices/<str:name>", views.delete_device_view, name="inventory-device-delete"),
    path("inventory/credentials", views.create_credential_profile_view, name="inventory-credentials-create"),
    path(
        "inventory/credentials/<str:name>",
        views.credential_profile_detail_view,
        name="inventory-credentials",
    ),
    path(
        "inventory/import-network",
        views.import_network_inventory_view,
        name="inventory-import-network",
    ),
    path(
        "inventory/cleanup-discovered",
        views.cleanup_discovered_devices_view,
        name="inventory-cleanup-discovered",
    ),
    path("scan", views.scan_inventory_view, name="scan"),
    path("scan/status", views.scan_status_view, name="scan-status"),
    path("scan/latest", views.get_latest_scan_view, name="scan-latest"),
    path("api/scan/history", views.scan_history_view, name="scan-history"),
    path("api/scan/trends", views.scan_trends_view, name="scan-trends"),
    path("api/compliance/summary", views.compliance_summary_view, name="compliance-summary"),
    path("api/compliance/by-site", views.compliance_by_site_view, name="compliance-by-site"),
    path("api/compliance/export", views.compliance_export_view, name="compliance-export"),
    path("api/compliance/report/send", views.compliance_report_send_view, name="compliance-report-send"),
    path("api/policies/groups", views.group_policies_dispatch, name="group-policies"),
    path("api/policies/groups/<str:group_name>", views.group_policy_delete, name="group-policy-delete"),
    path("api/settings/backup/compliance-report-test", views.compliance_report_test_view, name="compliance-report-test"),
    path("api/admin/backup-data", views.backup_data_view, name="backup-data"),
    path("api/audit", views.audit_events_view, name="audit-events"),
    path("api/audit/export", views.audit_export_view, name="audit-export"),
    path("api/security/audit/summary", views.security_audit_summary_view, name="security-audit-summary"),
    path("api/security/audit/runs", views.security_audit_runs_view, name="security-audit-runs"),
    path("api/security/audit/export", views.security_audit_export_view, name="security-audit-export"),
    path("api/security/audit/run", views.security_audit_run_view, name="security-audit-run"),
    path(
        "api/security/audit/findings/<int:finding_id>/ack",
        views.security_finding_ack_view,
        name="security-finding-ack",
    ),
    path("oxidized/sync", views.sync_oxidized_view, name="oxidized-sync"),
]
